spring:
  config:
    import: optional:configserver:http://localhost/8888
  applicatio:
  name: discovery-services
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceiUrl:
        defaultzone: http://{eureka.instance.hostname}/${server.post}/eureka/
server:
  port: 8761
